### ISSUE TITLE
Design Mentors Page

### ISSUE THREAD

**Issue by ykarim** [ykarim/openmrs-contrib-gci-site#11]
Design the full Mentors page based off the chosen theme. Design must also be mobile-friendly.

Requirements for the mentors page include: (note that you can change the order of this info and skip some parts)
* Navbar
    * Must contain logo used for site (could be combination of GCI and OpenMRS)
    * Must contain links to all 5 pages of site
* Current Mentor Cards (will include admins)
    * Each card will expand to contain mentor profile pic, name, OpenMRS ID, history with OpenMRS, links to GitHub/OpenMRS Talk profile, and other information deemed necessary)
* Roles of Mentors
* How to become a mentor
* FAQ (maybe)
* Footer

Note that the exact text doesn't have to be present. You may use sample text like "lorem ipsum dolor sit amet". We just need to see where all the information will go on the page.

Submit the design as a PDF/png in a professional format under designs/final-designs directory (this directory may need to be created). The design must include the webpage as shown on a computer and on mobile.

**Comment by Pmutkure009** [comment]
I will work on the Mentors Page!

**Comment by Pmutkure009** [comment]
Great! will wait till 22 :)

**Comment by ykarim** [comment]
Hey @JyothsnaAshok , this task is now ready for work. The following resources may assist you: https://github.com/satvikshri/OpenMRS-submissions/tree/master/homepageui and https://github.com/satvikshri/OpenMRS-submissions/tree/master/mentorsUI. Note that the .ai file contains the design and is an Adobe Illustrator file. 

The given resource is a theme and you are required to redesign though some elements of the page may remain the same. **You are free to fully redesign the page to your liking though you must keep the same theme (color palette and navbar)**

Some notes about the current design include:
* In the mentor pop-up we need an easy format to display contributions. A table like format that looks nice would work. 
* Pagination shouldn't be needed for the org as it's not a really large list. Try to find a better way to condense the info. Shrink the images perhaps. (Pagination might be needed but it's highly not preferred)
* Also the large title "Google Code-in 2018 with OpenMRS" seems irrelevant as students would already know what the site is for from many different places.
* The search bar is better spanning across the whole page rather than a small section
* Rarely do students ever know mentors by their face. Fit in names and role somewhere onto the mentor icon. PS: Recatangle cards may help with this.

**Comment by ykarim** [comment]
FYI the footer can be skipped as this will be done in a separate task.

**Comment by Pmutkure009** [comment]
So, should I keep the header same, or should I redesign it too (In accordance with the Theme).

**Comment by Pmutkure009** [comment]
Hey, where can I get the summary of a particular mentors contribution?
I think it will be easier to design the pop-up after seeing that!

And sorry for being late doing this, I was really busy last few days because its just start of semester :)

**Comment by ykarim** [comment]
@Pmutkure009 For contributions, we're planning on putting GitHub activity to OpenMRS repo's. This could either be the repo's themselves that a user has made commits/PR's to or the actual commits/PR's themselves. We also plan to include any information on projects a user has worked on in JIRA. Again this will either be the projects themselves (preferred) or the contributions made such as bugs found, issues resolved, or etc. Hope this helps!

**Comment by ykarim** [comment]
Cant really tell where the logo would go without seeing the proposed design, but sure yes feel free to include the colored or black and white logo alongside a link to a mentor's Talk profile!

**Comment by ykarim** [comment]
PR merged at: #37 and e4714e4ad8f9cd05d82d14b1c42f69c1738f8155 Thanks!
