### ISSUE TITLE
Design Help Page

### ISSUE THREAD

**Issue by ykarim** [ykarim/openmrs-contrib-gci-site#13]
Design the full Contact page based off the chosen theme. Design must also be mobile-friendly.

Requirements for the Contact page include: (note that you can change the order of this info and skip some parts)
* Navbar
    * Must contain logo used for site (could be combination of GCI and OpenMRS)
    * Must contain links to all 5 pages of site
* Must include these and what they're used for (student help cases)
    * OpenMRS Talk
    * OpenMRS GCI Telegram
    * OpenMRS IRC (maybe embedded)
    * OpenMRS Helpdesk
    * OpenMRS Wiki
    * Common issues students face and how to resolve them (Ex: JIRA signup must be done through helpdesk)
* Footer

Submit the design as a PDF/png in a professional format under designs/final-designs directory (this directory may need to be created). The design must include the webpage as shown on a computer and on mobile.

**Comment by ykarim** [comment]
Well its not ready to work yet until 12/22 at 12:00 AM when the theme is finalized but I'll mark it as In Progress for now

**Comment by ykarim** [comment]
Hey @satvikshri , this task is now ready for work. The following resources may assist you: https://github.com/satvikshri/OpenMRS-submissions/tree/master/homepageui and https://github.com/satvikshri/OpenMRS-submissions/tree/master/contactUI. Note that the .ai file contains the design and is an Adobe Illustrator file. 

The given resource is a theme and you are required to redesign though some elements of the page may remain the same. **You are free to fully redesign the page to your liking though you must keep the same theme (color palette and navbar)**

Some notes about the current design include:
* The first one seems good. It's just inconsistent font sizes that stick out
* Also, the navbar should include Contact as an option though this is a minor detail.
* It may be better to have the info on one side rather than alternate right and left. This makes it easier to read as users don't have to shift their eyes constantly.
* Also the large title "Google Code-in 2018 with OpenMRS" seems irrelevant as students would already know what the site is for from many different places.

**Comment by ykarim** [comment]
FYI the footer can be skipped as this will be done in a separate task.

**Comment by satvikshri** [comment]
Hey Yusuf!
I have a doubt regarding your suggestions.

> Also, the navbar should include Contact as an option though this is a minor detail.

Since this is the contact page itself, what will the contact as an option on the navbar do?

**Comment by ykarim** [comment]
Closed in #35 Thanks @satvikshri !
