### ISSUE TITLE
Descriptive README.md

### ISSUE THREAD

**Issue by ykarim** [ykarim/openmrs-contrib-gci-site#2]
Create a README.md that accurately displays the purpose of this project and how to contribute/build the site. Follow structure of other OpenMRS README files. 

May help to comment the content you plan to put on the README here before writing it all out.

**Comment by ibtehajraza** [comment]
Hi Yusuf Karim, Is there any issue that I can contribute to? Please let me know I'm in the learning phase of react and have strong hold on Angular and Java Script.

**Comment by Bisht13** [comment]
Hey @ykarim, [here](https://github.com/ykarim/openmrs-contrib-gci-site/pull/3) is my PR, added most of the basic and needed stuff.

**Comment by Bisht13** [comment]
> Hi Yusuf Karim, Is there any issue that I can contribute to? Please let me know I'm in the learning phase of react and have strong hold on Angular and Java Script.

Hey@ibtehajraza the whole website is building so this is just the beginning, more issues are coming up. You may checkout any of them and contribute :smiley:
