### ISSUE TITLE
Design Footer

### ISSUE THREAD

**Issue by ykarim** [ykarim/openmrs-contrib-gci-site#32]
Design the full footer based off the chosen theme. Design must also be mobile-friendly.

The following resources may assist you: https://github.com/satvikshri/OpenMRS-submissions/tree/master/homepageui

Some notes: 
* The footer navigation must be changed as those buttons are huge and not convenient. Plus, they're extremely hard to read because of their color. Not really modern design
* Maybe provide more helpful info necessary to place. Look at footers for popular sites and do research.

**Comment by riskycase** [comment]
Hey @ykarim, I'd take up this issue

**Comment by ykarim** [comment]
Thanks @riskycase !
